import { Link } from 'react-router-dom';
import { ArrowRight, Banknote, Leaf, Map, Sprout, Store } from 'lucide-react';

export default function Landing() {
  return <main className="landing-page">
    <header className="landing-nav"><Link to="/" className="landing-brand"><span className="brand-mark"><Leaf size={21}/></span><span><b>Krishi Sahayak</b><small>From seed to sale</small></span></Link><nav><a href="#how-it-works">How it works</a><Link to="/privacy">Privacy</Link><Link className="nav-signin" to="/login">Sign in</Link></nav></header>
    <section className="landing-hero"><div className="hero-copy"><span className="hero-kicker"><Sprout size={16}/> A practical farm workspace</span><h1>Make every season easier to manage.</h1><p>Keep your farm details, crop plans, and money records together. Krishi Sahayak gives farmers one clear place to track the work from sowing through sale.</p><div className="hero-actions"><Link className="primary-button" to="/login?mode=register">Create a farmer account <ArrowRight size={17}/></Link><Link className="text-link" to="/login">Sign in</Link></div><small>Dashboard navigation in English and Kannada</small></div><div className="hero-scene" role="img" aria-label="Illustration of a farm field at sunrise"><div className="scene-sun"/><div className="scene-hill hill-back"/><div className="scene-hill hill-front"/><div className="field-row row-one"/><div className="field-row row-two"/><div className="scene-label"><Map size={15}/> Your farm, in one view</div></div></section>
    <section className="landing-proof" id="how-it-works"><div className="proof-heading"><span>BUILT AROUND THE FARMER'S DAY</span><h2>Plan the work. Know the numbers. Find your next step.</h2></div><div className="feature-grid"><article><span><Map/></span><h3>Keep farm records</h3><p>Save farms and the crops growing on each one, with dates and field details in one place.</p></article><article><span><Banknote/></span><h3>Track income and costs</h3><p>Record sales and expenses, then see your totals and net balance from your own entries.</p></article><article><span><Store/></span><h3>Prepare for market</h3><p>Create a crop listing with quantity, expected price, harvest date, and location.</p></article></div></section>
    <section className="landing-cta"><div><span>START WITH THE NEXT THING</span><h2>Set up your farm workspace.</h2></div><Link className="primary-button" to="/login?mode=register">Create your account <ArrowRight size={17}/></Link></section>
    <footer className="landing-footer"><Link to="/">Krishi Sahayak</Link><span>Farm records and planning for growers.</span><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></footer>
  </main>;
}
